import "~/styles/globals.css";

import { Roboto } from 'next/font/google'
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "CLT Cloud - A Google Drive Clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en" className={`${roboto.className}`}>
      <body>{children}</body>
    </html>
  );
}